name: fox-sql-review-test
# on: [pull_request]
# on: [push]

on:
  push:
    branches:
      - 'master'


jobs:
  sql-review:
    runs-on: ubuntu-latest
    name: SQL Review
    steps:
      - uses: actions/checkout@v3
      - name: Check SQL
        # You can change it to a specific version like bytebase/sql-review-action@0.0.4
        # We suggest using the latest version through the tag. Check it at https://github.com/Bytebase/sql-review-action/tags
        uses: bytebase/sql-review-action@main
        with:
          # override-file-path: "<Your SQL review rules configuration file path>, ie: ./sql-review-override.yml "
          template-id: bb.sql-review.dev # "<SQL review rule template id> , should be one of bb.sql-review.prod or bb.sql-review.dev" 
          database-type: POSTGRES # "<The database type>"
          file-pattern:  ^db/.*\.sql$  # "<The file pattern for your SQL files>"