name: fox-sql-review-dev
# on: [pull_request]
# on: [push]

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - develop

jobs:

  split-schema-sql-file:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Split schema.sql into small sql
        run: |
          awk '{filename = "./db/dev/migration-liquibase/test/schema-split." int((NR-1)/1000) ".sql"; print >> filename}' ./temp/schema.sql
          pwd && ls -al ./db/dev/migration-liquibase/test/schema-split
        shell: bash


  sql-review-dev:
    runs-on: ubuntu-latest
    name: SQL Review
    steps:
      - uses: actions/checkout@v3
      - name: Check DEV SQL SCRIPT
        # You can change it to a specific version like bytebase/sql-review-action@0.0.4
        # We suggest using the latest version through the tag. Check it at https://github.com/Bytebase/sql-review-action/tags
        uses: bytebase/sql-review-action@main
        with:
          # override-file-path: "<Your SQL review rules configuration file path>, ie: ./sql-review-override.yml "
          template-id: bb.sql-review.dev # "<SQL review rule template id> , should be one of bb.sql-review.prod or bb.sql-review.dev" 
          database-type: POSTGRES # "<The database type>"
          file-pattern:  ^db/dev/.*/.*\.sql$  # "<The file pattern for your SQL files>"
      - name: Notify SQL Review result
        # if: failure()
        if: always()
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel-id: ${{ secrets.SLACK_WEBHOOK_CHANNEL }}
          payload: |
            {
              "text": "GitHub Action SQL syntax review result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action SQL syntax review result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
  sql-deploy-to-dev:
    needs: sql-review-dev
    runs-on: ubuntu-latest
    name: Run SQL CD Here
    steps:
      - uses: actions/checkout@v3
      - name: You can run SQL CD job here
        run: |
          echo "Run CD pipeline here "

      - name: Notify SQL CD pipeline result
        if: always()
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel-id: ${{ secrets.SLACK_WEBHOOK_CHANNEL }}
          payload: |
            {
              "text": "GitHub Action SQL CD pipeline: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action SQL CD pipeline:: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }